# Generated by Django 4.2.5 on 2023-11-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genzApp', '0002_authors_category_newsletter_userprofile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazineStories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('title', models.CharField(blank=True, max_length=225, null=True)),
                ('intro', models.TextField()),
                ('body', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genzApp.authors')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genzApp.category')),
            ],
        ),
    ]
