# Generated by Django 4.2.5 on 2023-12-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzApp', '0010_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
