# Generated by Django 4.2.5 on 2024-01-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzApp', '0016_magazinestories_imagesource_magazinestories_storyby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinestories',
            name='category',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='category',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
