# Generated by Django 4.2.5 on 2024-01-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzApp', '0017_alter_magazinestories_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinestories',
            name='category',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='magazinestories',
            name='imageSource',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='magazinestories',
            name='storyBy',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='magazinestories',
            name='title',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='imageSource',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='storyBy',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='title',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
