# Generated by Django 4.2.5 on 2024-01-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzApp', '0018_alter_magazinestories_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazinestories',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazinestories',
            name='storyBy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='magazinestories',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='intro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='storyBy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stories',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
