# Generated by Django 4.2.5 on 2024-01-07 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genzApp', '0020_notificationread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationread',
            name='message',
        ),
        migrations.RemoveField(
            model_name='notificationread',
            name='title',
        ),
    ]
