# Generated by Django 4.1.1 on 2024-02-03 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzApp', '0025_magazine_adminuser_magazine_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
