# Generated by Django 4.1.1 on 2024-02-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genzApp', '0027_remove_user_code_passwordreset'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordreset',
            name='new_password',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
