# Generated by Django 4.1.1 on 2024-02-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genzApp', '0028_passwordreset_new_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='new_password',
        ),
    ]
